language: c
compiler: gcc

# We need to be root to install the SDL2 packages
sudo: true

env:
 global:
  # Where the compiler looks when searching for static libraries
  - LIBRARY_PATH=.:$LIBRARY_PATH
  # Idem for `#include`d headers
  - CPATH=.:$CPATH
  - C_INCLUDE_PATH=.:$C_INCLUDE_PATH

before_install:
 # Refreshing the APT cache doesn't hurt
 - sudo apt-get update
 # We obviously need the SDL installed
 - sudo apt-get install --yes libasound2-dev libdbus-1-dev libegl1-mesa-dev libgl1-mesa-dev libgles2-mesa-dev libglu1-mesa-dev libibus-1.0-dev libmirclient-dev libpulse-dev libsdl2-2.0-0 libsndio-dev libudev-dev libwayland-dev libx11-dev libxcursor-dev libxext-dev libxi-dev libxinerama-dev libxkbcommon-dev libxrandr-dev libxss-dev libxt-dev libxv-dev libxxf86vm-dev libsdl2-dev
 # Install the dependencies listed in the install_deps.sh script
 - sudo ./install_deps.sh

script:
 - make
