language: c
compiler: gcc

# We need to be root to install the SDL2 packages
sudo: true


before_install:
 # Install the dependencies from the install_deps.sh script
 - sudo ./install_deps.sh

script:
 - make
