language: c
compiler: gcc

sudo: true

before_install:
 - sudo apt-get update
 - sudo apt-get install libsdl2-dev

script:
 - shopt -s extglob
 - wget -Olog.h 'https://drive.google.com/uc?id=1abiyY2pTgT5ADHqDJs_0YMSv3cDdelAq'
 - wget -Oliblog.a 'https://drive.google.com/uc?id=10YVKVufUiqVuuotLexu5ZQHP4d_UvKq0'
 - gcc !(test*).c -osdlife -llog -lSDL2
